### PR TITLE
Add support for the stack command

### PR DESCRIPTION
**Pull request by Alphare**
I am note certain what the git equivalent is, so I left it unimplemented (and hidden) for now.

Related: I think the keyboard shortcuts should be part of the config file, although we would have to warn about conflicts and unreachable chords.

### CODE REVIEW

**Comment by vamolessa** [comment]
Since there could be no git equivalent, couldn't this be a custom command?
like, you can put this on the `.verco/custom_commands.txt` file:

```
s hg stack --color always
```

and then execute it with `xs`

**Comment by Alphare** [comment]
Well custom commands are more for unusual or... well truly custom commands I would say. I can see adding support for selecting through the stack to get the `export` or `update`ing to any given revision in the stack for example.

The `hg stack` command is used by pretty much all users of topic.

**Comment by vamolessa** [comment]
From what I understand, this is a mercurial extension. So people may not have that command installed. I'm not sure how we should deal with that or even if it should be added as a regular command.

Maybe this is something that could be a verco extension itself?

**Comment by Alphare** [comment]
It could be gated behind a config option like `hg.topic_enabled` if you're uncomfortable with it being a top-level command?

**Pull request closed without merging**
