### PR TITLE
tui: use alternate screen to not pollute output and prevent backscroll

### PR DESCRIPTION
**Pull request by Alphare**

### CODE REVIEW

**Comment by Alphare** [comment]
Note: maybe we should use a drop guard of some kind to trigger the exit of this alternate screen and raw mode, but that's for another PR

**Comment by vamolessa** [comment]
Ok, this gonna sound funny, but I actually like it this way ahhaah

Every now and then I exit verco after using a log command to then run a cli command using info that was displayed on screen (such as commit hashes, etc).

What do you think?

**Comment by Alphare** [comment]
Then it should be a config option I guess! 

I understand your use case, but I think I'm not the only one with that need. AFAICT there is no config file yet, am I wrong?

**Comment by vamolessa** [comment]
There is no config for now. A flag makes sense (either through cli param or config file). Not yet sure which one should be the default!

**Comment by Alphare** [comment]
I think most people expect a TUI to enter an alternate screen, like vim, less, htop, etc. but I may be biased.

Would you be open to adding a config file? In a TOML format I suppose?

**Comment by vamolessa** [comment]
I really liked the idea of a small dependency count project.
At the same time, I understand the value it would bring (also trying to think of what other configs could enter the "vercorc").

Anyways, I think you're right regarding the alternate screen, it should be the default.
To deal with my use case, maybe we could add a command to copy the hash of a commit and then there would be no need for a config file (at least for now?).

**Comment by Alphare** [comment]
You can use shift+mouse1 to select, I guess?

I also see the value in a low-dependency project, but a means of configuration is far from code bloat.

**Pull request merged**
