### PR TITLE
More robust log manipulation for shortcuts

### PR DESCRIPTION
**Pull request by Alphare**
The current log replacement for shortcuts does not work well when hashes are
referred to inside revision descriptions.

This change does 2 things:
    - Uses a more robust template string that does not exhibit the above bug
    - Drops one of the two VCS calls necessary to dramatically improve
      performance in big repositories

This requires the addition of a dependency on `regex`, which is one of the
best crates in the ecosystem and will most likely be used in other future
patches.

### CODE REVIEW

**Comment by Alphare** [comment]
Two notes:

The regex is re-compiled at every invocation. It should not really matter since it's small, but in general, they should be in a `lazy_static`.

Also I think this notion of shortcuts would be better served with a more intuitive and robust "selection mode", so maybe this whole dance is temporary

**Comment by vamolessa** [comment]
This is cool

At the same time, however, I'd like to design something more robust to deal with inputing commit hashes. The current system has some limitations such as: only the first 26 visible or something hashes have shortcuts; you can only use them if you first run `log`;

Some suggestions:
- auto completion (maybe a background job that fetches some hashes for completion)
- a log view that lets us select a commit (and parsing it's hash into a verco register or clipboard, or something) and maybe do something with it
- an action just for copying (or saving to a register) a commit hash. we could have then actions that operate on the clipboard (or saved register)

Gonna open an issue for this

**Comment by Alphare** [comment]
Oh absolutely. This is just a temporary fix, because right now the output is slower than it needs and bugged. I agree that the log view (and the general handling) should be rethought, as mentioned in #24

**Comment by vamolessa** [comment]
With the new reelase, the hash is parsed directly from the raw output, which is then formatted to the screen. We can revisit this solution if we get to the point of, say, reconstruct the log graph inside verco.

**Comment by vamolessa** [comment]
closing this since we no longer use log shortcuts instead focusing on a 'menu' like interface to drive quick checkouts/merges/diffs

**Pull request closed without merging**
